initialize errors HashSet without high initial capacity
RustScan/RustScan pull request #532
Opened 2024-01-06 10:28 UTC by fabianbees

In most cases it is not expected to have that many errors, which causes an increase of the HashSet, it shouldn't be necessary to pre-allocate that much memory for potential errors.

fixes:
- #447
- #523

2024-04-06 20:32 UTC, bee-san requested changes
commenting to see if CI will run... it is not?

2024-04-06 20:58 UTC, bee-san commented
Hi! Mind pushing an empty commit? CI has failed to pick this up and I think it'll only pick it up on a new commit? 🤔

2024-04-07 06:59 UTC, fabianbees commented
CI is not running, because the Build-Workflow somehow requires an approval from a maintainer:
![image](https://github.com/RustScan/RustScan/assets/28726756/04befc2b-e144-4379-b5e0-1b0120733b2e)

2024-04-07 07:08 UTC, bee-san commented
> CI is not running, because the Build-Workflow somehow requires an approval from a maintainer: ![image](https://private-user-images.githubusercontent.com/28726756/320258791-04befc2b-e144-4379-b5e0-1b0120733b2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzM5NzQsIm5iZiI6MTcxMjQ3MzY3NCwicGF0aCI6Ii8yODcyNjc1Ni8zMjAyNTg3OTEtMDRiZWZjMmItZTE0NC00Mzc5LWI1ZTAtMWIwMTIwNzMzYjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3MDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMWYwYWFmZDE0ZjAxYzEyM2UzMzc3MjE4ZjhmYWM0OGJhM2EzYjY0ZjEyYWY3YzEwMTI4MTg3ZWU5ZGU4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6cRvyVRqucd_w6MhvygcoBuUI-xsbpn66wCHrjLCVWI)

Yes, that's fine. Before it wasn't running at all, and the emtpy commit kicked GitHub into seeing it had _something_ to do here :)

CI is running!

2024-04-07 07:10 UTC, merged

2024-04-07 07:10 UTC, bee-san commented
thank you!!

2024-04-07 07:18 UTC, fabianbees commented
Your welcome! :)