Fix typo
RustScan/RustScan pull request #621
Opened 2024-07-16 12:56 UTC by madneal

2024-08-07 07:59 UTC, bee-san requested changes
some few comments, thanks for ur contrib :)

2024-08-07 07:59 UTC, bee-san commented on README.md
> +[discord]: https://discord.skerritt.blog "Discord blog"
SSL does not exist for this domain

2024-08-07 07:59 UTC, bee-san commented on src/input.rs
> +/// - Discord  <https://discord.skerritt.blog>
same

2024-08-07 07:59 UTC, bee-san commented on src/main.rs
> +        r#": https://discord.skerritt.blog         :"#,
same

2024-11-04 11:10 UTC, PsypherPunk commented on src/main.rs
> +    // udp is an option to do an udp scan
All the other changes make sense but my take is that this is already correct: if this is pronounced "yoo-dee-pee", it should use "a" as an article.

2024-11-04 12:07 UTC, closed without merging